name: Schedule Events in GitHub Actions

on:
  schedule:
    - cron: '4 17 * * *'
  pull_request:
    types: [opened,reopened]
  issues:
    types: [opened, closed]
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy to which environment"
        default: "dev"
        required: true
        type: 'choice'
        options:
          - staging
          - production
          - dev
      debug:
        description: "Enable Debug"
        type: boolean
        default: false
        required: false
      version:
        description: "Version to Deploy"
        required: false
        type: string

        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: echo "Hello, Scheduled Workflow!"
      - name: Print Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Debug : ${{ github.event.inputs.debug }}"
          echo "Version: ${{ github.event.inputs.version}}"
        

